name: Alpha Caller
on:
  workflow_call:
    inputs:
      image:
        required: false
        type: string
      args:
        required: false
        type: string
      options:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      image:
        required: false
        description: "image and tag to run"
        default: docker.io/library/hello-world:latest
        type: string
      options:
        required: false
        description: "image options"
        type: string
      args:
        required: false
        description: "image args"
        type: string

jobs:
  alpha-caller:
    runs-on: ubuntu-latest
    outputs:
      runtime-data: ${{ steps.alpha-caller-run-img.outputs.runtime-data }}
    steps:
      - uses: SwordFisherL42/dashboard/.github/actions/docker-run-img@main
        name: Run Docker image
        id: alpha-caller-run-img
        with:
          image: ${{ inputs.image }}
          args: ${{ inputs.args }}
          options: ${{ inputs.options }}
      - name: Check Outputs
        run: |
          echo ${{ steps.alpha-caller-run-img.outputs.runtime-data }}
  beta-caller:
    needs: alpha-caller
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - name: Second job getter
        run: |
          echo "Runtime data is ${{ needs.alpha-caller.outputs.runtime-data }}"
