name: NXM-Update
on:
  push:
    branches: [ "main", "actions-runner" ]
  workflow_dispatch:
env:
  VERSION: 1.0.0
  MOD_NAME: Glowing Red Eyes Reshade
  MOD_SUMMARY: Glowing Red Eyes Reshade
  MOD_DESCRIPTION: Glowing Red Eyes Reshade

jobs:
  update-mod-page:
    runs-on: ubuntu-latest
    environment:
      name: deployment
      url: https://www.nexusmods.com/users/77539483
    steps:
      - uses: actions/checkout@v3
      - name: Get Description
        run: export DESCRIPTION=$(`cat $GITHUB_WORKSPACE/description`)
      - name: Update NXM Details
        run: |
          python $GITHUB_WORKSPACE/.github/workflows/nxm_update.py \
            --cookie='${{ secrets.NEXUS_API_COOKIE }}' \
            --mod=${{ secrets.MOD_ID }} \
            --version='${{ env.VERSION }}' \
            --name='${{ env.MOD_NAME }}' \
            --description='$DESCRIPTION' \
            --summary='${{ env.MOD_SUMMARY }}'