name: NXM-Update
on:
  push:
    branches: [ "main", "actions-runner" ]
  workflow_dispatch:
env:
  MOD_NAME: NXM CICD Staging
  MOD_ID: 5890

jobs:
  update-mod-page:
    runs-on: ubuntu-latest
    environment:
      name: nxm-core
      url: https://www.nexusmods.com/bladeandsorcery/mods/${{ env.MOD_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Update Mod Details
        run: |
          export DESCRIPTION=$(<$GITHUB_WORKSPACE/.nxm/description) &&
          export SUMMARY=$(<$GITHUB_WORKSPACE/.nxm/summary) &&
          python $GITHUB_WORKSPACE/.github/workflows/nxm_update.py \
            --cookie='${{ secrets.NXM_COOKIE }}' \
            --mod=${{ env.MOD_ID }} \
            --name='${{ env.MOD_NAME }}' \
            --assembly_info=$GITHUB_WORKSPACE/.nxm/AssemblyInfo.cs