name: NXM-Update
on:
  push:
    branches: [ "main", "actions-runner" ]
  workflow_dispatch:
env:
  MOD_NAME: NXM CICD Staging
  MOD_SUMMARY: Glowing Red Eyes Reshade

jobs:
  update-mod-page:
    runs-on: ubuntu-latest
    environment:
      name: deployment
      url: https://www.nexusmods.com/users/77539483
    steps:
      - uses: actions/checkout@v3
      - name: Update Mod Details
        run: |
          export DESCRIPTION=$(<$GITHUB_WORKSPACE/.nxm/description) &&
          python $GITHUB_WORKSPACE/.github/workflows/nxm_update.py \
            --cookie='${{ secrets.NEXUS_API_COOKIE }}' \
            --mod=${{ secrets.MOD_ID }} \
            --description='$DESCRIPTION'
            --name='${{ env.MOD_NAME }}' \
            --summary='${{ env.MOD_SUMMARY }}' \
            --assembly_info=$GITHUB_WORKSPACE/.nxm/AssemblyInfo.cs