name: Orchestrator Runtime
on:
  push:
    branches: ["orc-test"]
  workflow_dispatch:

jobs:
  run-orc-steps:
    runs-on: ubuntu-latest
    outputs:
      info: ${{ steps.run-orchestrator.outputs.info }}
      status: ${{ steps.run-orchestrator.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Sample App
        id: run-orchestrator
        run: |
          set +e
          output=$(python $GITHUB_WORKSPACE/.github/workflows/sample_app.py fail 2>&1)
          echo "status=$output" >> "$GITHUB_OUTPUT"
  run-orc-notify:
    needs: run-orc-steps
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - name: Print the global variable
        run: |
          echo "Run info is ${{ needs.run-orc-steps.outputs.status }}"
    # uses: ./.github/workflows/orc_notifier.yml
    # if: always()
    # with:
    #   run-status: "0"
    #   run-info: ${{ needs.run-orc-steps.env.run_info }}
    #     # secrets: inherit
    #     # secrets:
    #     #   envPAT: ${{ secrets.envPAT }}