name: Orchestrator Runtime
on:
  push:
    branches: ["orc-test"]
  workflow_dispatch:

jobs:
  run-orc-steps:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.run-orchestrator.outputs.status }}
      environment: ${{ steps.run-orchestrator.outputs.environment }}
      commit: ${{ steps.run-orchestrator.outputs.commit }}
      github_link: ${{ steps.run-orchestrator.outputs.github_link }}
      error: ${{ steps.run-orchestrator.outputs.error }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Sample App
        id: run-orchestrator
        env:
          GITHUB_ACTIONS: "true"
        run: |
          python $GITHUB_WORKSPACE/.github/workflows/sample_app.py fail
  run-orc-notify:
    needs: run-orc-steps
    uses: ./.github/workflows/orc_notifier.yml
    if: success() || failure()
    with:
      status: ${{ needs.run-orc-steps.outputs.status }}
      environment: ${{ needs.run-orc-steps.outputs.environment }}
      commit: ${{ needs.run-orc-steps.outputs.commit }}
      github_link: ${{ needs.run-orc-steps.outputs.github_link }}
      error: ${{ needs.run-orc-steps.outputs.error }}
        # secrets: inherit
        # secrets:
        #   envPAT: ${{ secrets.envPAT }}