name: Orchestrator Runtime
on:
  push:
    branches: ["orc-test"]
  workflow_dispatch:

jobs:
  run-orc-steps:
    runs-on: ubuntu-latest
    outputs:
      info: ${{ steps.run-orchestrator.outputs.info }}
      status: ${{ steps.run-orchestrator.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      # - name: Print the global variable
      #   run: echo "run_info is ${{ env.run_info }}"
      # - name: Modify the global variable
      #   id: modify-step
      #   run: |
      #     echo "info=new_run_info" >> "$GITHUB_OUTPUT"
      - name: Run Sample App
        id: run-orchestrator
        run: |
          output="$(path/myExcecutable-bin 2>&1)"
          echo $output
          exit_code=$?
          echo "info=$output" >> "$GITHUB_OUTPUT"
          echo "status=$exit_code" >> "$GITHUB_OUTPUT"
  run-orc-notify:
    needs: run-orc-steps
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - name: Print the global variable
        run: |
          echo "Run info is ${{ needs.run-orc-steps.outputs.info }}"
          echo "Run status exit code is ${{ needs.run-orc-steps.outputs.info }}"
    # uses: ./.github/workflows/orc_notifier.yml
    # if: always()
    # with:
    #   run-status: "0"
    #   run-info: ${{ needs.run-orc-steps.env.run_info }}
    #     # secrets: inherit
    #     # secrets:
    #     #   envPAT: ${{ secrets.envPAT }}