name: Orchestrator Runtime
on:
  workflow_dispatch:

jobs:
  run-orc-steps:
    runs-on: ubuntu-latest
    outputs:
      info: ${{ steps.run-orchestrator.outputs.info }}
    steps:
      - uses: actions/checkout@v4
      # - name: Print the global variable
      #   run: echo "run_info is ${{ env.run_info }}"
      # - name: Modify the global variable
      #   id: modify-step
      #   run: |
      #     echo "info=new_run_info" >> "$GITHUB_OUTPUT"
      - name: Run Sample App
        id: run-orchestrator
        run: |
          output=$(python $GITHUB_WORKSPACE/.github/workflows/sample_app.py pass)
          exit_code=$?
          echo "info=$output" >> "$GITHUB_OUTPUT"
  run-orc-notify:
    needs: run-orc-steps
    runs-on: ubuntu-latest
    if: '!canceled()'
    steps:
      - name: Print the global variable
        run: |
          echo "run_info is ${{ needs.run-orc-steps.outputs.info }}"
    # uses: ./.github/workflows/orc_notifier.yml
    # if: always()
    # with:
    #   run-status: "0"
    #   run-info: ${{ needs.run-orc-steps.env.run_info }}
    #     # secrets: inherit
    #     # secrets:
    #     #   envPAT: ${{ secrets.envPAT }}