name: Orchestration Notifier
on:
  workflow_call:
    inputs:
      runtime-data:
        required: true
        type: string
    # secrets:
    #   slack-token:
    #     required: true
  workflow_dispatch:


jobs:
  orchestrator-notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Notifier
        id: run-notify-app
        run: |
          python $GITHUB_WORKSPACE/.github/workflows/notifier.py --data='${{ inputs.runtime-data }}'
    