name: Orchestrator Runtime
on:
  push:
    branches: ["orc-test"]
  workflow_dispatch:

jobs:
  run-orc-steps:
    runs-on: ubuntu-latest
    outputs:
      runtime-data: ${{ steps.run-orchestrator.outputs.runtime-data }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Sample App
        id: run-orchestrator
        env:
          GITHUB_ACTIONS: "true"
        run: |
          python $GITHUB_WORKSPACE/.github/workflows/sample_app.py dne
  run-orc-notify:
    needs: run-orc-steps
    uses: ./.github/workflows/orc_notifier.yml
    if: success() || failure()
    with:
      runtime-data: ${{ needs.run-orc-steps.outputs.runtime-data }}
        # secrets: inherit
        # secrets:
        #   envPAT: ${{ secrets.envPAT }}