name: Orchestrator Runtime
on:
  push:
    branches: ["orc-test"]
  workflow_dispatch:

jobs:
  run-orc-steps:
    runs-on: ubuntu-latest
    outputs:
      info: ${{ steps.run-orchestrator.outputs.info }}
      status: ${{ steps.run-orchestrator.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Sample App
        id: run-orchestrator
        run: |
          set +e
          output=$(python $GITHUB_WORKSPACE/.github/workflows/sample_app.py fail)
          export exit_code=$?
          echo "status="$output"" >> "$GITHUB_OUTPUT"
          echo "$output"
          echo "info="$exit_code"" >> "$GITHUB_OUTPUT"
          echo "Exit code is $exit_code"
  run-orc-notify:
    needs: run-orc-steps
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - name: Print the global variable
        run: |
          echo "Run info is ${{ needs.run-orc-steps.outputs.status }}"
          echo "Run Exit Code is ${{ needs.run-orc-steps.outputs.info }}"
    # uses: ./.github/workflows/orc_notifier.yml
    # if: always()
    # with:
    #   run-status: "0"
    #   run-info: ${{ needs.run-orc-steps.env.run_info }}
    #     # secrets: inherit
    #     # secrets:
    #     #   envPAT: ${{ secrets.envPAT }}