name: Orchestrator Runtime
on:
  push:
    branches: ["orc-test"]
  workflow_dispatch:

jobs:
  run-orc-steps:
    runs-on: ubuntu-latest
    outputs:
      info: ${{ steps.run-orchestrator.outputs.info }}
      status: ${{ steps.run-orchestrator.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Sample App
        id: run-orchestrator
        run: |
          set +e
          output=$(python $GITHUB_WORKSPACE/.github/workflows/sample_app.py fail 2>&1)
          exit_code=$?
          echo "info="$output"" >> "$GITHUB_OUTPUT"
          echo "status="$exit_code"" >> "$GITHUB_OUTPUT"
          set -e
          echo "$output"
          exit $exit_code
  run-orc-notify:
    needs: run-orc-steps
    uses: ./.github/workflows/orc_notifier.yml
    if: success() || failure()
    with:
      run-status: ${{ needs.run-orc-steps.outputs.status }}
      run-info: ${{ needs.run-orc-steps.outputs.info }}
        # secrets: inherit
        # secrets:
        #   envPAT: ${{ secrets.envPAT }}