name: Orchestration Notifier
on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      environment:
        required: true
        type: string
      commit:
        type: string
      github_link:
        type: string
      error:
        type: string
    # secrets:
    #   slack-token:
    #     required: true
  workflow_dispatch:


jobs:
  orchestrator-notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Notifier
        id: run-notify-app
        run: |
          python $GITHUB_WORKSPACE/.github/workflows/notifier.py --status="${{ inputs.status }}" \
          --environment="${{ inputs.environment }}" \
          --commit="${{ inputs.commit }}" \
          --link="${{ inputs.github_link }}" \
          --error="${{ inputs.error }}"

    