name: Persistant Steps
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-persistant-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Step
        run: |
          python $GITHUB_WORKSPACE/.github/workflows/sample_app.py fail
      - name: Make File
        run: |
          echo "Command Run Here" > $GITHUB_WORKSPACE/build_status.log
      - name: Read Status
        run: |
          echo $(cat $GITHUB_WORKSPACE/build_status.log)